package com.hotel.service;

import com.hotel.dao.AnalyticsDAO;
import com.hotel.dao.RoomDAO;
import com.hotel.model.DynamicPricingRecommendation;
import com.hotel.model.RevenueOptimizationReport;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * DynamicPricingServiceLiveTest - Tests live Gemini AI dynamic pricing analysis and recommendations.
 */
public class DynamicPricingServiceLiveTest {

    @Test
    public void testLiveGeminiDynamicPricingAnalysis() {
        GeminiService gemini = new GeminiService();
        if (!gemini.isApiKeyConfigured()) {
            System.out.println("Skipping live test: GEMINI_API_KEY not configured");
            return;
        }

        DynamicPricingService service = new DynamicPricingService(new RoomDAO(), new AnalyticsDAO(), gemini);
        long start = System.currentTimeMillis();
        RevenueOptimizationReport report = service.generateReport(true);
        long elapsed = System.currentTimeMillis() - start;

        System.out.println("==================================================");
        System.out.println("STAGE 19 LIVE GEMINI DYNAMIC PRICING REPORT:");
        System.out.println("Elapsed Time       : " + elapsed + " ms");
        System.out.println("Generated By AI    : " + report.isFromAI());
        System.out.println("Strategy Headline  : " + report.getOverallStrategyHeadline());
        System.out.println("Market Summary     : " + report.getAiMarketSummary());
        System.out.println("Occupancy Rate     : " + report.getOverallOccupancyRate() + "%");
        System.out.println("Weekend Factor     : " + report.isWeekend());
        System.out.println("Recommendations Count: " + (report.getRecommendations() != null ? report.getRecommendations().size() : 0));
        if (report.getRecommendations() != null) {
            for (DynamicPricingRecommendation rec : report.getRecommendations()) {
                System.out.println(" - " + rec.getTypeName() + ": Current $" + rec.getCurrentPrice() 
                        + " -> Rec $" + rec.getRecommendedPrice() + " (" + rec.getAdjustmentPercent() + "%) [" 
                        + rec.getStrategy() + "] - " + rec.getEconomicRationale());
            }
        }
        System.out.println("==================================================");

        assertNotNull("Report must not be null", report);
        assertNotNull("Strategy headline must not be null", report.getOverallStrategyHeadline());
        assertFalse("Strategy headline must not be empty", report.getOverallStrategyHeadline().trim().isEmpty());
        assertNotNull("Recommendations list must not be null", report.getRecommendations());
        assertFalse("Recommendations list must not be empty", report.getRecommendations().isEmpty());
    }
}
