package com.hotel.model;

import java.io.Serializable;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 * ChatMessage Model - Represents an interaction turn between guest/user and the AI Hotel Concierge.
 */
public class ChatMessage implements Serializable {

    private String sender;       // "user" or "assistant"
    private String message;
    private String timestamp;
    private boolean fromAI;      // true if generated by Gemini API, false if rule-based fallback

    public ChatMessage() {
        this.timestamp = LocalTime.now().format(DateTimeFormatter.ofPattern("hh:mm a"));
    }

    public ChatMessage(String sender, String message, boolean fromAI) {
        this.sender = sender;
        this.message = message;
        this.fromAI = fromAI;
        this.timestamp = LocalTime.now().format(DateTimeFormatter.ofPattern("hh:mm a"));
    }

    public ChatMessage(String sender, String message, String timestamp, boolean fromAI) {
        this.sender = sender;
        this.message = message;
        this.timestamp = timestamp;
        this.fromAI = fromAI;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public boolean isFromAI() {
        return fromAI;
    }

    public void setFromAI(boolean fromAI) {
        this.fromAI = fromAI;
    }
}
